name: GitHub Actions Demo
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{matrix.node-version }}
        uses: actions/setup-node#v3

